# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_auto_20170602_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_num',
            field=models.CharField(max_length=8),
        ),
    ]
