# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courseCode',
            new_name='course_code',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='idNum',
            new_name='id_num',
        ),
    ]
